FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o auth-service main.go

FROM alpine:3.18
WORKDIR /app

COPY --from=builder /app/auth-service .
COPY .env . 

EXPOSE 3000
ENV PORT=3000 \
    MONGODB_URI=mongodb://mongo:27017 \
    JWT_SECRET=supersecretkey

CMD ["./auth-service"]
